spring.application.name=mediconnect
spring.config.import=optional:file:.env[.properties]
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
spring.threads.virtual.enabled=true

app.security.jwt-secret=${JWT_SECRET}
app.security.jwt-expiration-minutes=${JWT_EXPIRATION_MINUTES:60}
app.bootstrap.admin-email=${DEV_ADMIN_EMAIL:}
app.bootstrap.admin-password=${DEV_ADMIN_PASSWORD:}

openfda.base-url=${OPENFDA_BASE_URL:https://api.fda.gov}

management.endpoints.web.exposure.include=health,info,metrics,mediconnect
management.endpoint.health.show-details=when_authorized
management.info.env.enabled=true
info.app.name=MediConnect Enterprise Pro
info.app.java=${java.version}

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
