package com.mediconnect.appointment.application;

import java.time.*; import java.util.*;
import com.mediconnect.appointment.api.*; import com.mediconnect.appointment.domain.*; import com.mediconnect.appointment.infrastructure.*; import com.mediconnect.doctor.domain.DoctorEntity; import com.mediconnect.doctor.infrastructure.DoctorRepository; import com.mediconnect.observability.BusinessMetrics; import com.mediconnect.office.domain.OfficeEntity; import com.mediconnect.office.infrastructure.OfficeRepository; import com.mediconnect.patient.domain.PatientEntity; import com.mediconnect.patient.infrastructure.PatientRepository; import com.mediconnect.shared.exception.*;
import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class AppointmentService {
 private final AppointmentRepository appointmentRepository; private final DoctorRepository doctorRepository; private final PatientRepository patientRepository; private final OfficeRepository officeRepository; private final AppointmentMapper mapper; private final AppointmentPolicy policy; private final BusinessMetrics metrics; private final ZoneId zoneId;
 public AppointmentService(AppointmentRepository appointmentRepository,DoctorRepository doctorRepository,PatientRepository patientRepository,OfficeRepository officeRepository,AppointmentMapper mapper,AppointmentPolicy policy,BusinessMetrics metrics,ZoneId zoneId){this.appointmentRepository=appointmentRepository;this.doctorRepository=doctorRepository;this.patientRepository=patientRepository;this.officeRepository=officeRepository;this.mapper=mapper;this.policy=policy;this.metrics=metrics;this.zoneId=zoneId;}
 @PreAuthorize("hasRole('PATIENT')") @Transactional public AppointmentResponse createForPatient(String patientEmail,CreateAppointmentRequest request){policy.validateBookingWindow(request.startTime(),request.endTime());PatientEntity patient=patientRepository.findByUserEmailIgnoreCase(patientEmail).orElseThrow(()->new ResourceNotFoundException("Patient profile not found."));DoctorEntity doctor=doctorRepository.findByIdForUpdate(request.doctorId()).orElseThrow(()->new ResourceNotFoundException("Doctor not found."));if(!doctor.isActive())throw new BusinessRuleException("The selected doctor is not active.");OfficeEntity office=officeRepository.findById(request.officeId()).orElseThrow(()->new ResourceNotFoundException("Office not found."));if(!office.isActive())throw new BusinessRuleException("The selected office is not active.");boolean overlaps=appointmentRepository.existsDoctorOverlap(doctor.getId(),request.startTime(),request.endTime(),AppointmentStatus.CANCELLED);if(overlaps)throw new AppointmentConflictException("The doctor already has an appointment that overlaps this time window.");return mapper.toResponse(appointmentRepository.save(new AppointmentEntity(patient,doctor,office,request.startTime(),request.endTime())));}
 @PreAuthorize("hasRole('PATIENT')") @Transactional(readOnly=true) public List<AppointmentResponse> listForPatient(String patientEmail){PatientEntity patient=patientRepository.findByUserEmailIgnoreCase(patientEmail).orElseThrow(()->new ResourceNotFoundException("Patient profile not found."));return appointmentRepository.findByPatientIdOrderByStartTimeDesc(patient.getId()).stream().map(mapper::toResponse).toList();}
 @PreAuthorize("hasRole('PATIENT')") @Transactional public AppointmentResponse cancelForPatient(String patientEmail,UUID appointmentId){PatientEntity patient=patientRepository.findByUserEmailIgnoreCase(patientEmail).orElseThrow(()->new ResourceNotFoundException("Patient profile not found."));AppointmentEntity appointment=findEntity(appointmentId);if(!appointment.getPatient().getId().equals(patient.getId()))throw new org.springframework.security.access.AccessDeniedException("Patients may only cancel their own appointments.");if(appointment.getStatus()!=AppointmentStatus.SCHEDULED)throw new BusinessRuleException("Only scheduled appointments can be cancelled.");try{policy.validatePatientCancellation(appointment.getStartTime());}catch(LateCancellationException ex){metrics.recordLateCancellation();throw ex;}appointment.cancel();return mapper.toResponse(appointment);}
 @PreAuthorize("hasRole('DOCTOR')") @Transactional(readOnly=true) public List<AppointmentResponse> todayForDoctor(String doctorEmail){DoctorEntity doctor=doctorRepository.findByUserEmailIgnoreCase(doctorEmail).orElseThrow(()->new ResourceNotFoundException("Doctor profile not found."));LocalDate today=LocalDate.now(zoneId);Instant start=today.atStartOfDay(zoneId).toInstant();Instant end=today.plusDays(1).atStartOfDay(zoneId).toInstant();return appointmentRepository.findByDoctorIdAndStartTimeGreaterThanEqualAndStartTimeLessThanOrderByStartTimeAsc(doctor.getId(),start,end).stream().map(mapper::toResponse).toList();}
 @PreAuthorize("hasRole('DOCTOR')") @Transactional public AppointmentResponse completeForDoctor(String doctorEmail,UUID appointmentId){AppointmentEntity appointment=requireAssignedDoctor(doctorEmail,appointmentId);if(appointment.getStatus()!=AppointmentStatus.SCHEDULED)throw new BusinessRuleException("Only scheduled appointments can be completed.");appointment.complete();return mapper.toResponse(appointment);}
 @Transactional(readOnly=true) public AppointmentEntity requireAssignedDoctor(String doctorEmail,UUID appointmentId){DoctorEntity doctor=doctorRepository.findByUserEmailIgnoreCase(doctorEmail).orElseThrow(()->new ResourceNotFoundException("Doctor profile not found."));AppointmentEntity appointment=findEntity(appointmentId);if(!appointment.getDoctor().getId().equals(doctor.getId()))throw new org.springframework.security.access.AccessDeniedException("Doctors may only operate on appointments assigned to them.");return appointment;}
 @Transactional(readOnly=true) public AppointmentEntity findEntity(UUID appointmentId){return appointmentRepository.findById(appointmentId).orElseThrow(()->new ResourceNotFoundException("Appointment not found."));}
}
