package com.mediconnect.doctor.application;

import java.util.List; import java.util.UUID;
import com.mediconnect.auth.domain.*; import com.mediconnect.auth.infrastructure.UserRepository; import com.mediconnect.doctor.api.*; import com.mediconnect.doctor.domain.DoctorEntity; import com.mediconnect.doctor.infrastructure.*; import com.mediconnect.shared.exception.*; import com.mediconnect.specialty.domain.SpecialtyEntity; import com.mediconnect.specialty.infrastructure.SpecialtyRepository;
import org.springframework.cache.annotation.*; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class DoctorService {
 private final DoctorRepository doctorRepository; private final UserRepository userRepository; private final SpecialtyRepository specialtyRepository; private final DoctorMapper doctorMapper; private final PasswordEncoder passwordEncoder;
 public DoctorService(DoctorRepository doctorRepository,UserRepository userRepository,SpecialtyRepository specialtyRepository,DoctorMapper doctorMapper,PasswordEncoder passwordEncoder){this.doctorRepository=doctorRepository;this.userRepository=userRepository;this.specialtyRepository=specialtyRepository;this.doctorMapper=doctorMapper;this.passwordEncoder=passwordEncoder;}
 @Transactional(readOnly=true) @Cacheable(value="doctorsBySpecialty",key="#specialtyId") public List<DoctorResponse> listBySpecialty(UUID specialtyId){if(!specialtyRepository.existsById(specialtyId))throw new ResourceNotFoundException("Specialty not found.");return doctorRepository.findBySpecialtyIdAndActiveTrueOrderByLastNameAsc(specialtyId).stream().map(doctorMapper::toResponse).toList();}
 @PreAuthorize("hasRole('ADMIN')") @Transactional @CacheEvict(value="doctorsBySpecialty",key="#request.specialtyId()") public DoctorResponse createDoctor(CreateDoctorRequest request){String email=request.email().trim().toLowerCase();if(userRepository.existsByEmailIgnoreCase(email))throw new DuplicateResourceException("An account already exists with that email.");if(doctorRepository.existsByMedicalLicenseIgnoreCase(request.medicalLicense().trim()))throw new DuplicateResourceException("A doctor already exists with that medical license.");SpecialtyEntity specialty=specialtyRepository.findById(request.specialtyId()).orElseThrow(()->new ResourceNotFoundException("Specialty not found."));UserEntity user=userRepository.save(new UserEntity(email,passwordEncoder.encode(request.temporaryPassword()),Role.ROLE_DOCTOR));DoctorEntity doctor=new DoctorEntity(user,specialty,request.firstName().trim(),request.lastName().trim(),request.medicalLicense().trim());return doctorMapper.toResponse(doctorRepository.save(doctor));}
 public DoctorEntity findByEmail(String email){return doctorRepository.findByUserEmailIgnoreCase(email).orElseThrow(()->new ResourceNotFoundException("Doctor profile not found."));}
}
